apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicjunkies-backend-depl
  namespace: test
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: musicjunkies-backend
  template: 
    metadata:
      labels:
        app: musicjunkies-backend
    spec:
      dnsPolicy: Default
      containers:
        - name: musicjunkies-backend
          image: vigneshbondugula/mj-backend:latest
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: musicjunkies-backend-svc
  namespace: test
spec:
  type: ClusterIP
  selector:
    app: musicjunkies-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000