apiVersion: apps/v1
kind: Deployment
metadata:
  name: musicjunkies-backend-depl
  namespace: default
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: musicjunkies-backend
  template: 
    metadata:
      labels:
        app: musicjunkies-backend
    spec:
      dnsPolicy: Default
      containers:
        - name: musicjunkies-backend
          image: vigneshbondugula/mj-backend:latest
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: data
              mountPath: /app/logs/
      volumes:
      - name: data
        hostPath:
          path: /home/docker/logs
---
apiVersion: v1
kind: Service
metadata:
  name: musicjunkies-backend-svc
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: musicjunkies-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000